/**
 * @author lusinabrian on 27/11/17.
 * @notes: Action types to be used by reducer
 */

export const FETCH_CURRENCY_LIST_REQUEST = "FETCH_CURRENCY_LIST_REQUEST";
export const FETCH_CURRENCY_LIST_SUCCESS = "FETCH_CURRENCY_LIST_SUCCESS";
export const FETCH_CURRENCY_LIST_FAILURE = "FETCH_CURRENCY_LIST_FAILURE";
export const CHANGE_BASE_CURRENCY = "CHANGE_BASE_CURRENCY";
export const CHANGE_QUOTE_CURRENCY = "CHANGE_QUOTE_CURRENCY";

