export const NAVIGATE_TO_CURRENCY_LIST_SCREEN = "NAVIGATE_TO_CURRENCY_LIST_SCREEN";
export const NAVIGATE_TO_HOME_SCREEN = "NAVIGATE_TO_HOME_SCREEN";
export const NAVIGATE_TO_SETTINGS_SCREEN = "NAVIGATE_TO_SETTINGS_SCREEN";
export const NAVIGATE_TO_THEMES_SCREEN = "NAVIGATE_TO_THEMES_SCREEN";
