export const SWAP_CURRENCY_ACTION = "SWAP_CURRENCY_ACTION";
export const CHANGE_CURRENCY_AMOUNT = "CHANGE_CURRENCY_AMOUNT";
export const FETCH_CONVERSION_RATES_REQUEST = "FETCH_CONVERSION_RATES_REQUEST";
export const FETCH_CONVERSION_RATES_FAILURE = "FETCH_CONVERSION_RATES_FAILURE";
export const FETCH_CONVERSION_RATES_SUCCESS = "FETCH_CONVERSION_RATES_SUCCESS";